spring:
  profiles:
    active: dev
  session:
    store-type: redis
  jmx:
    default-domain: iptv

swagger:
  enable: true
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
    use-generated-keys: true